### ISSUE TITLE
Deprecated: Methods with the same name as their class PHP 7

### ISSUE THREAD

**Issue by clintre** [llagerlof/MyLogPHP#2]
In PHP 7 there is a new notice "Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP".

Will need to changed the MyLogPHP class or function.

**Comment by llagerlof** [comment]
I will change the constructor to `__construct()`. Let me install PHP 7 to make some testing and I will update here.

Thanks.

**Comment by llagerlof** [comment]
@clintre, I just saw your pull request and tested it in my current PHP 5.5. Looks fine. I will test it later in PHP 7 and merge it. Thank you.

**Comment by clintre** [comment]
No problem, love the script.

**Comment by llagerlof** [comment]
Pull Request #3 merged.
