### ISSUE TITLE
Notice: Undefined variable: headers

### ISSUE THREAD

**Issue by pquerner** [llagerlof/MyLogPHP#4]
I know you disabled the error, but why dont you just check if $headers is empty. And if its not you can use the fwrite?

**Comment by llagerlof** [comment]
@pquerner But are you having any problems with the class?

**Comment by pquerner** [comment]
If you run tests which utilizes this class its annoying you have to deal with that suppressed warning. Other than that, no problems whatsoever.

**Comment by llagerlof** [comment]
Supressed warnings removed.
