### ISSUE TITLE
Enabling Checking

### ISSUE THREAD

**Issue by pquerner** [llagerlof/MyLogPHP#5]
Currently it is checked if logging is enabled every time something is logged. This should be saved to a class property, so it saves time and memory.

**Comment by pmanolak** [comment]
@llagerlof  do we have any further update about this change?

**Comment by llagerlof** [comment]
> @llagerlof do we have any further update about this change?

Since this is an improvement, not a bug fix, it wasn't my top priority. But is an easy change. I will do it in the next days.

**Comment by pmanolak** [comment]
Much appreciate for your response!

Regards,
Panagiotis.

**Comment by llagerlof** [comment]
Fixed in f0748111dd78c7d0059b0273c72e7dbf1d404548

**Comment by pmanolak** [comment]
Thanks a lot for your work!
