### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Class 'MyLogPHP' not found

### ISSUE THREAD

**Issue by pmanolak** [llagerlof/MyLogPHP#6]
New issue experienced with version 1.2.18 which was not existed in earlier versions.

Part of php script:

```
  16         include('MyLogPHP.class.php');
  17         $log = new MyLogPHP('debug.log.csv');
  18         $log->info('test_log_line', 'INFO');
```

Error returned:

```
panagiotis.manolakos@ljw5xtn2-ath:/var/www/html/api_guid_test$ php api_guid_test.php 
PHP Fatal error:  Uncaught Error: Class 'MyLogPHP' not found in /var/www/html/api_guid_test/api_guid_test.php:17
Stack trace:
#0 {main}
   thrown in /var/www/html/api_guid_test/api_guid_test.php on line 17
 panagiotis.manolakos@ljw5xtn2-ath:/var/www/html/api_guid_test$ 
```

Do we know why this occurred?

As per change log, the only change in that version is the adding of namespace. Not sure if its related.
Please note that the class file is remained untouched as downloaded from here.

Thanks a lot in advance.

Regards,
Panagiotis.

**Comment by pmanolak** [comment]
It seems as temporary workaround that works if adding also the namespace as bellow:

```
$log = new MyLogPHP\MyLogPHP('debug.log.csv');
```

Is this the expected behavior? In that case the README.md should be updated.

**Comment by llagerlof** [comment]
README updated in f0748111dd78c7d0059b0273c72e7dbf1d404548

- Minimum PHP version 5.3 (because the namespace).
- With the namespace, the object should by instantiated as @pmanolak pointed out:
`$log = new MyLogPHP\MyLogPHP('debug.log.csv');`

**Comment by pmanolak** [comment]
Much appreciate! Thanks!
